# Generated by Django 2.0.3 on 2018-03-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='name',
            field=models.CharField(default='tovar', max_length=64),
            preserve_default=False,
        ),
    ]
