# Generated by Django 2.0.3 on 2018-03-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_object_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='test', max_length=64),
            preserve_default=False,
        ),
    ]
