# Generated by Django 2.0.3 on 2018-03-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180329_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='object',
            name='stats',
            field=models.TextField(default='Thats so powerfull!'),
        ),
    ]
