# Generated by Django 2.0.3 on 2018-04-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20180405_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies_genres', to='movies.Genre'),
        ),
    ]
