# Generated by Django 2.0.3 on 2018-04-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20180405_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='preview',
            field=models.ImageField(upload_to='static/movies/images/'),
        ),
    ]
