# Generated by Django 2.0.3 on 2018-04-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20180405_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='preview',
            field=models.ImageField(upload_to='static/movies/images/previews/'),
        ),
    ]
