# Generated by Django 2.0.3 on 2018-04-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20180405_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='preview',
            field=models.ImageField(upload_to='previews/'),
        ),
    ]
