# Generated by Django 2.0.3 on 2018-04-08 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0006_auto_20180406_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_to_watch', models.ManyToManyField(related_name='users_plan_to_watch', to='movies.Movie')),
            ],
        ),
        migrations.RemoveField(
            model_name='rate',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plan_to_watch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='watched',
        ),
        migrations.RemoveField(
            model_name='user',
            name='watching',
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='watched',
            field=models.ManyToManyField(related_name='users_watched', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='watching',
            field=models.ManyToManyField(related_name='users_watching', to='movies.Movie'),
        ),
    ]
