# Generated by Django 2.0.3 on 2018-04-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20180409_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='users_favorite', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='plan_to_watch',
            field=models.ManyToManyField(blank=True, related_name='users_plan_to_watch', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='watched',
            field=models.ManyToManyField(blank=True, related_name='users_watched', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='watching',
            field=models.ManyToManyField(blank=True, related_name='users_watching', to='movies.Movie'),
        ),
    ]
